apiVersion: v1
kind: Service
metadata:
  name: server-ext-connection
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: gateway
      nodePort: 30000
   selector:
    app: controlserver