apiVersion: v1
kind: Service
metadata:
  name: server-int-connection
spec:
  type: ClusterIP
  ports:
    - port: 8083
      name: controlserver
  selector:
    app: controlserver
---
apiVersion: v1
kind: Service
metadata:
  name: nodeserver
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: nodeserver
  selector:
    app: nodeserver
---
apiVersion: v1
kind: Service
metadata:
  name: validationserver
spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: validationserver
  selector:
    app: validationserver
---
